# Generated by Django 4.2.1 on 2023-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='feature_images/car.jpeg', upload_to='feature_images/'),
        ),
    ]
